use inputbot::KeybdKey;

#[inline(always)]
fn send(key: KeybdKey) {
    key.press();
    key.release();
}

#[inline(always)]
pub fn gen_shin(key: i32) {
    match key {
        24 => send(KeybdKey::ZKey),
        26 => send(KeybdKey::XKey),
        28 => send(KeybdKey::CKey),
        29 => send(KeybdKey::VKey),
        31 => send(KeybdKey::BKey),
        33 => send(KeybdKey::NKey),
        35 => send(KeybdKey::MKey),
        36 => send(KeybdKey::ZKey),
        38 => send(KeybdKey::XKey),
        40 => send(KeybdKey::CKey),
        41 => send(KeybdKey::VKey),
        43 => send(KeybdKey::BKey),
        45 => send(KeybdKey::NKey),
        47 => send(KeybdKey::MKey),
        48 => send(KeybdKey::ZKey),
        50 => send(KeybdKey::XKey),
        52 => send(KeybdKey::CKey),
        53 => send(KeybdKey::VKey),
        55 => send(KeybdKey::BKey),
        57 => send(KeybdKey::NKey),
        59 => send(KeybdKey::MKey),
        60 => send(KeybdKey::AKey),
        62 => send(KeybdKey::SKey),
        64 => send(KeybdKey::DKey),
        65 => send(KeybdKey::FKey),
        67 => send(KeybdKey::GKey),
        69 => send(KeybdKey::HKey),
        71 => send(KeybdKey::JKey),
        72 => send(KeybdKey::QKey),
        74 => send(KeybdKey::WKey),
        76 => send(KeybdKey::EKey),
        77 => send(KeybdKey::RKey),
        79 => send(KeybdKey::TKey),
        81 => send(KeybdKey::YKey),
        83 => send(KeybdKey::UKey),
        84 => send(KeybdKey::QKey),
        86 => send(KeybdKey::WKey),
        88 => send(KeybdKey::EKey),
        89 => send(KeybdKey::RKey),
        91 => send(KeybdKey::TKey),
        93 => send(KeybdKey::YKey),
        95 => send(KeybdKey::UKey),
        _ => {},
    };
}

#[inline(always)]
pub fn vr_chat(key: i32) {
    match key {
        36 => send(KeybdKey::OtherKey(90)),
        37 => send(KeybdKey::OtherKey(188)),
        38 => send(KeybdKey::OtherKey(88)),
        39 => send(KeybdKey::OtherKey(190)),
        40 => send(KeybdKey::OtherKey(67)),
        41 => send(KeybdKey::OtherKey(86)),
        42 => send(KeybdKey::OtherKey(191)),
        43 => send(KeybdKey::OtherKey(66)),
        44 => send(KeybdKey::OtherKey(96)),
        45 => send(KeybdKey::OtherKey(78)),
        46 => send(KeybdKey::OtherKey(110)),
        47 => send(KeybdKey::OtherKey(77)),
        48 => send(KeybdKey::OtherKey(65)),
        49 => send(KeybdKey::OtherKey(75)),
        50 => send(KeybdKey::OtherKey(83)),
        51 => send(KeybdKey::OtherKey(76)),
        52 => send(KeybdKey::OtherKey(68)),
        53 => send(KeybdKey::OtherKey(70)),
        54 => send(KeybdKey::OtherKey(186)),
        55 => send(KeybdKey::OtherKey(71)),
        56 => send(KeybdKey::OtherKey(98)),
        57 => send(KeybdKey::OtherKey(72)),
        58 => send(KeybdKey::OtherKey(99)),
        59 => send(KeybdKey::OtherKey(74)),
        60 => send(KeybdKey::OtherKey(81)),
        61 => send(KeybdKey::OtherKey(73)),
        62 => send(KeybdKey::OtherKey(87)),
        63 => send(KeybdKey::OtherKey(79)),
        64 => send(KeybdKey::OtherKey(69)),
        65 => send(KeybdKey::OtherKey(82)),
        66 => send(KeybdKey::OtherKey(80)),
        67 => send(KeybdKey::OtherKey(84)),
        68 => send(KeybdKey::OtherKey(101)),
        69 => send(KeybdKey::OtherKey(89)),
        70 => send(KeybdKey::OtherKey(102)),
        71 => send(KeybdKey::OtherKey(85)),
        72 => send(KeybdKey::OtherKey(49)),
        73 => send(KeybdKey::OtherKey(56)),
        74 => send(KeybdKey::OtherKey(50)),
        75 => send(KeybdKey::OtherKey(57)),
        76 => send(KeybdKey::OtherKey(51)),
        77 => send(KeybdKey::OtherKey(52)),
        78 => send(KeybdKey::OtherKey(48)),
        79 => send(KeybdKey::OtherKey(53)),
        80 => send(KeybdKey::OtherKey(104)),
        81 => send(KeybdKey::OtherKey(54)),
        82 => send(KeybdKey::OtherKey(105)),
        83 => send(KeybdKey::OtherKey(55)),
        84 => send(KeybdKey::OtherKey(112)),
        85 => send(KeybdKey::OtherKey(119)),
        86 => send(KeybdKey::OtherKey(113)),
        87 => send(KeybdKey::OtherKey(120)),
        88 => send(KeybdKey::OtherKey(114)),
        89 => send(KeybdKey::OtherKey(115)),
        90 => send(KeybdKey::OtherKey(121)),
        91 => send(KeybdKey::OtherKey(116)),
        92 => send(KeybdKey::OtherKey(111)),
        93 => send(KeybdKey::OtherKey(117)),
        94 => send(KeybdKey::OtherKey(106)),
        95 => send(KeybdKey::OtherKey(118)),
        _ => {},
    };
}
