use rdev::{simulate, EventType, Key};

#[inline]
fn press(event: &EventType) {
    if let Ok(()) = simulate(event) {
        ()
    }
}

#[inline]
pub fn send(key: Key) {
    press(&EventType::KeyPress(key));
    press(&EventType::KeyRelease(key));
}

pub const GEN: fn(i32) = |key| match key {
    24 => send(Key::KeyZ),
    26 => send(Key::KeyX),
    28 => send(Key::KeyC),
    29 => send(Key::KeyV),
    31 => send(Key::KeyB),
    33 => send(Key::KeyN),
    35 => send(Key::KeyM),
    36 => send(Key::KeyZ),
    38 => send(Key::KeyX),
    40 => send(Key::KeyC),
    41 => send(Key::KeyV),
    43 => send(Key::KeyB),
    45 => send(Key::KeyN),
    47 => send(Key::KeyM),
    48 => send(Key::KeyZ),
    50 => send(Key::KeyX),
    52 => send(Key::KeyC),
    53 => send(Key::KeyV),
    55 => send(Key::KeyB),
    57 => send(Key::KeyN),
    59 => send(Key::KeyM),
    60 => send(Key::KeyA),
    62 => send(Key::KeyS),
    64 => send(Key::KeyD),
    65 => send(Key::KeyF),
    67 => send(Key::KeyG),
    69 => send(Key::KeyH),
    71 => send(Key::KeyJ),
    72 => send(Key::KeyQ),
    74 => send(Key::KeyW),
    76 => send(Key::KeyE),
    77 => send(Key::KeyR),
    79 => send(Key::KeyT),
    81 => send(Key::KeyY),
    83 => send(Key::KeyU),
    84 => send(Key::KeyQ),
    86 => send(Key::KeyW),
    88 => send(Key::KeyE),
    89 => send(Key::KeyR),
    91 => send(Key::KeyT),
    93 => send(Key::KeyY),
    95 => send(Key::KeyU),
    _ => (),
};

pub const VR: fn(i32) = |key| match key {
    36 => send(Key::Unknown(90)),
    37 => send(Key::Unknown(188)),
    38 => send(Key::Unknown(88)),
    39 => send(Key::Unknown(190)),
    40 => send(Key::Unknown(67)),
    41 => send(Key::Unknown(86)),
    42 => send(Key::Unknown(191)),
    43 => send(Key::Unknown(66)),
    44 => send(Key::Unknown(96)),
    45 => send(Key::Unknown(78)),
    46 => send(Key::Unknown(110)),
    47 => send(Key::Unknown(77)),
    48 => send(Key::Unknown(65)),
    49 => send(Key::Unknown(75)),
    50 => send(Key::Unknown(83)),
    51 => send(Key::Unknown(76)),
    52 => send(Key::Unknown(68)),
    53 => send(Key::Unknown(70)),
    54 => send(Key::Unknown(186)),
    55 => send(Key::Unknown(71)),
    56 => send(Key::Unknown(98)),
    57 => send(Key::Unknown(72)),
    58 => send(Key::Unknown(99)),
    59 => send(Key::Unknown(74)),
    60 => send(Key::Unknown(81)),
    61 => send(Key::Unknown(73)),
    62 => send(Key::Unknown(87)),
    63 => send(Key::Unknown(79)),
    64 => send(Key::Unknown(69)),
    65 => send(Key::Unknown(82)),
    66 => send(Key::Unknown(80)),
    67 => send(Key::Unknown(84)),
    68 => send(Key::Unknown(101)),
    69 => send(Key::Unknown(89)),
    70 => send(Key::Unknown(102)),
    71 => send(Key::Unknown(85)),
    72 => send(Key::Unknown(49)),
    73 => send(Key::Unknown(56)),
    74 => send(Key::Unknown(50)),
    75 => send(Key::Unknown(57)),
    76 => send(Key::Unknown(51)),
    77 => send(Key::Unknown(52)),
    78 => send(Key::Unknown(48)),
    79 => send(Key::Unknown(53)),
    80 => send(Key::Unknown(104)),
    81 => send(Key::Unknown(54)),
    82 => send(Key::Unknown(105)),
    83 => send(Key::Unknown(55)),
    84 => send(Key::Unknown(112)),
    85 => send(Key::Unknown(119)),
    86 => send(Key::Unknown(113)),
    87 => send(Key::Unknown(120)),
    88 => send(Key::Unknown(114)),
    89 => send(Key::Unknown(115)),
    90 => send(Key::Unknown(121)),
    91 => send(Key::Unknown(116)),
    92 => send(Key::Unknown(111)),
    93 => send(Key::Unknown(117)),
    94 => send(Key::Unknown(106)),
    95 => send(Key::Unknown(118)),
    _ => (),
};
